FROM docker.elastic.co/kibana/kibana-oss:6.7.1

RUN bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-security/opendistro_security_kibana_plugin-0.9.0.0.zip